import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Placeholder Firebase options used by CI and local static analysis.
///
/// The real `lib/firebase_options.dart` is generated by `flutterfire configure`
/// and is gitignored because it contains project-specific values. CI copies
/// this file to `lib/firebase_options.dart` so that `flutter analyze` and
/// `flutter test` can compile `lib/main.dart`.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return const FirebaseOptions(
      apiKey: 'demo-api-key',
      appId: '1:000000000000:android:0000000000000000',
      messagingSenderId: '000000000000',
      projectId: 'ecosphere-demo',
    );
  }
}
