import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../../auth/presentation/providers/auth_controller.dart';
import '../../data/social_feed_repository.dart';
import '../../domain/social_post.dart';

/// State for the social feed
class SocialFeedState {
  final List<SocialPost> posts;
  final bool isLoading;
  final String? error;

  const SocialFeedState({
    this.posts = const [],
    this.isLoading = false,
    this.error,
  });

  SocialFeedState copyWith({
    List<SocialPost>? posts,
    bool? isLoading,
    String? error,
  }) {
    return SocialFeedState(
      posts: posts ?? this.posts,
      isLoading: isLoading ?? this.isLoading,
      error: error,
    );
  }
}

/// Controller for managing social feed
class SocialFeedController extends StateNotifier<SocialFeedState> {
  final SocialFeedRepository _repository;
  final String userId;

  SocialFeedController({
    required SocialFeedRepository repository,
    required this.userId,
  })  : _repository = repository,
        super(const SocialFeedState()) {
    loadFeed();
  }

  /// Load the feed
  Future<void> loadFeed() async {
    state = state.copyWith(isLoading: true, error: null);

    try {
      final posts = await _repository.getRecentPosts(limit: 50);
      state = state.copyWith(posts: posts, isLoading: false);
    } catch (e) {
      state = state.copyWith(
        isLoading: false,
        error: e.toString(),
      );
    }
  }

  /// Create a new post
  Future<void> createPost({
    required String content,
    required String userDisplayName,
    String? userPhotoUrl,
    String? activityId,
    String? activityType,
    double? carbonImpact,
    String? imageUrl,
  }) async {
    try {
      final post = SocialPost(
        id: '', // Will be generated by Firestore
        userId: userId,
        userDisplayName: userDisplayName,
        userPhotoUrl: userPhotoUrl,
        content: content,
        activityId: activityId,
        activityType: activityType,
        carbonImpact: carbonImpact,
        imageUrl: imageUrl,
        createdAt: DateTime.now(),
      );

      await _repository.createPost(post);
      
      // Reload feed to show new post
      await loadFeed();
    } catch (e) {
      state = state.copyWith(error: e.toString());
      rethrow;
    }
  }

  /// Toggle like on a post
  Future<void> toggleLike(String postId) async {
    try {
      final post = state.posts.firstWhere((p) => p.id == postId);
      
      if (post.isLikedBy(userId)) {
        await _repository.unlikePost(postId, userId);
      } else {
        await _repository.likePost(postId, userId);
      }

      // Update local state optimistically
      final updatedPosts = state.posts.map((p) {
        if (p.id == postId) {
          final newLikedBy = p.isLikedBy(userId)
              ? p.likedBy.where((id) => id != userId).toList()
              : [...p.likedBy, userId];
          
          return SocialPost(
            id: p.id,
            userId: p.userId,
            userDisplayName: p.userDisplayName,
            userPhotoUrl: p.userPhotoUrl,
            content: p.content,
            activityId: p.activityId,
            activityType: p.activityType,
            carbonImpact: p.carbonImpact,
            imageUrl: p.imageUrl,
            likedBy: newLikedBy,
            commentCount: p.commentCount,
            createdAt: p.createdAt,
            metadata: p.metadata,
          );
        }
        return p;
      }).toList();

      state = state.copyWith(posts: updatedPosts);
    } catch (e) {
      state = state.copyWith(error: e.toString());
      rethrow;
    }
  }

  /// Delete a post
  Future<void> deletePost(String postId) async {
    try {
      await _repository.deletePost(postId);
      
      // Remove from local state
      final updatedPosts = state.posts.where((p) => p.id != postId).toList();
      state = state.copyWith(posts: updatedPosts);
    } catch (e) {
      state = state.copyWith(error: e.toString());
      rethrow;
    }
  }

  /// Refresh the feed
  Future<void> refresh() async {
    await loadFeed();
  }
}

/// Provider for SocialFeedController
final socialFeedControllerProvider =
    StateNotifierProvider<SocialFeedController, SocialFeedState>((ref) {
  final repository = ref.watch(socialFeedRepositoryProvider);
  final user = ref.watch(currentUserProvider);

  if (user == null) {
    throw Exception('User must be authenticated to access social feed');
  }

  return SocialFeedController(
    repository: repository,
    userId: user.uid,
  );
});
